name: Inputs Validation

on:

  pull_request:
    types: [opened, edited, reopened, synchronize, review_request_removed]
    branches:
      - 'main'
  
  push:
    tags:
      - '*'


jobs:
  
  validate:
    name: Inputs Validation

    outputs:
      TAG_NAME:
        ${{ steps.package.outputs.TAG_NAME }}
      PACKAGE_NAME:
        ${{ steps.package.outputs.PACKAGE_NAME }}
      PACKAGE_VERSION:
        ${{ steps.package.outputs.PACKAGE_VERSION }}
      PACKAGE_STATUS:
        ${{ steps.package.outputs.PACKAGE_STATUS }}
      PROTO_PATH:
        ${{ steps.package.outputs.PROTO_PATH }}
      TAG_CREATED_FLAG:
        ${{ steps.package.outputs.TAG_CREATED_FLAG }}
    
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Information
        id: package
        run:  |
              if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.ref_type }}" == "branch" ]; then
                TAG_NAME="${{ github.event.pull_request.title }}"
                TAG_CREATED_FLAG='false'
              else
                if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
                  TAG_NAME="${{ github.ref_name }}"
                  TAG_CREATED_FLAG='true'
                fi
              fi
              PACKAGE_NAME=`echo $TAG_NAME          | awk -F '-' '{print $1}'`
              PACKAGE_VERSION=`echo $TAG_NAME       | awk -F '-' '{print $2}'`
              PACKAGE_STATUS=`echo $TAG_NAME        | awk -F '-' '{print $3}'`
              # Hardcode PROTO_PATH to "contacts"
              PROTO_PATH="contacts"
              if  [[ "${PACKAGE_STATUS}" =~ "${{ vars.TAG_PRERELEASE_IDENTITY }}" ]]; then
                  PACKAGE_STATUS="-${PACKAGE_STATUS}";
              fi
              echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_OUTPUT"
              echo "PACKAGE_NAME=${PACKAGE_NAME}" >> "$GITHUB_OUTPUT"
              echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"
              echo "PACKAGE_STATUS=${PACKAGE_STATUS}" >> "$GITHUB_OUTPUT"
              echo "PROTO_PATH=${PROTO_PATH}" >> "$GITHUB_OUTPUT"
              echo "TAG_CREATED_FLAG=${TAG_CREATED_FLAG}" >> "$GITHUB_OUTPUT"
              echo "=== BUILD INFORMATION ====================================================================================="
              echo "»»» Tag Name: ${TAG_NAME}"
              echo "»»» Package Name: ${PACKAGE_NAME}"
              echo "»»» Package Version: ${PACKAGE_VERSION}"
              echo "»»» Package Status: ${PACKAGE_STATUS}"
              echo "»»» Proto Path: ${PROTO_PATH}"
              echo "»»» Tag Created Flag: ${TAG_CREATED_FLAG}"
              echo " "
      
      
      - name: Validations
        run:  |
              echo "=== VALIDATIONS =========================================================================================="
              echo "»»» Package Version: ${{ steps.package.outputs.PACKAGE_VERSION }}"
              digit_regex_pattern="^[0-9]+\.[0-9]+\.[0-9]+$"
              if  [[ ! "${{ steps.package.outputs.PACKAGE_VERSION }}" =~ $digit_regex_pattern ]]; then
                  echo "» Package Version is not correct!"
                  exit 1
                  else 
                  echo "»»» Version OK"
              fi
              echo " "
  
  