name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"

      - name: Disply name
        run: |
            mkdir mytest
            cd mytest 
            touch mytest.txt
            ls -a
